/**
 * Candidate ranking.
 *
 * Providers return results in *their* relevance order, which is tuned for
 * "pretty" rather than "actually this country". Taking result[0] is how a
 * tourism site ends up illustrating Uganda's lakeshore with Zanzibar. So every
 * candidate is scored across the ten dimensions the brief lists, and anything
 * that fails to clear ACCEPT_THRESHOLD is refused — an unresolved slot is a
 * better outcome than a wrong one.
 *
 * The single most important signal is `countryConflict`: the signature place
 * names of *other* countries in the register. A photo tagged "serengeti"
 * cannot represent Uganda no matter how beautiful it is.
 */

import { COUNTRIES, REGION, ALL_DESTINATIONS } from '../data/countries/index.js';
import { getCategory, roleOf } from '../data/categories.js';

export const ACCEPT_THRESHOLD = 42;

/** Terms that read as stock-library staging rather than real travel imagery. */
const INAUTHENTIC = [
  'isolated on white', 'white background', 'studio shot', 'mockup', 'copy space',
  'illustration', '3d render', 'clip art', 'vector', 'ai generated', 'generated by ai',
  'stock photo concept', 'green screen', 'template',
];

/** Words that suggest a captive or staged animal rather than a wild one. */
const CAPTIVE = ['zoo', 'captive', 'enclosure', 'cage', 'aquarium', 'circus', 'pet'];

const wordsOf = (text) => String(text ?? '').toLowerCase();

/**
 * Every signature term belonging to some *other* destination. Computed once
 * from the register, so adding a country automatically teaches every existing
 * country to avoid its landmarks.
 */
function conflictTermsFor(slug) {
  const terms = new Set();
  for (const dest of ALL_DESTINATIONS) {
    if (dest.slug === slug) continue;
    // The region shares its terms with everyone; it is not a conflict.
    if (dest.slug === REGION.slug) continue;
    for (const term of dest.signature) terms.add(term.toLowerCase());
  }
  // A country never conflicts with its own terms even if another country
  // happens to list a shared name (e.g. "rift valley").
  const own = new Set(
    (ALL_DESTINATIONS.find((d) => d.slug === slug)?.signature ?? []).map((t) =>
      t.toLowerCase(),
    ),
  );
  for (const t of own) terms.delete(t);
  return [...terms];
}

const CONFLICT_CACHE = new Map();
function conflicts(slug) {
  if (!CONFLICT_CACHE.has(slug)) CONFLICT_CACHE.set(slug, conflictTermsFor(slug));
  return CONFLICT_CACHE.get(slug);
}

/** All the text a candidate carries, lowercased and joined. */
function haystack(candidate) {
  return wordsOf(
    [candidate.description, candidate.photographer, ...(candidate.tags ?? [])].join(' '),
  );
}

/* ------------------------------------------------------------------ scoring */

/** 1. Country relevance — does anything say this is the right country? */
function scoreCountry(candidate, destination, text) {
  let score = 0;
  const name = destination.name.toLowerCase();
  if (text.includes(name)) score += 18;

  for (const term of destination.signature) {
    if (text.includes(term.toLowerCase())) {
      score += 14;
      break;
    }
  }
  for (const term of destination.strong ?? []) {
    if (text.includes(term.toLowerCase())) {
      score += 7;
      break;
    }
  }
  // Cap so one heavily-tagged photo cannot run away with the whole budget.
  return Math.min(score, 30);
}

/** 2. Category relevance — is it about the right *kind* of thing? */
function scoreCategory(candidate, entry, text) {
  const category = getCategory(entry.category);
  const queryTerms = entry.searchQuery
    .split(/\s+/)
    .map((t) => t.toLowerCase())
    .filter((t) => t.length > 3);

  const hits = queryTerms.filter((t) => text.includes(t)).length;
  let score = Math.min(hits * 5, 18);

  const titleWords = category.title
    .toLowerCase()
    .split(/[^a-z]+/)
    .filter((w) => w.length > 3);
  if (titleWords.some((w) => text.includes(w))) score += 4;

  return Math.min(score, 22);
}

/** 3+4. Visual quality and resolution. */
function scoreQuality(candidate) {
  const pixels = candidate.width * candidate.height;
  let score = 0;
  if (pixels >= 12_000_000) score += 12;
  else if (pixels >= 6_000_000) score += 10;
  else if (pixels >= 3_000_000) score += 7;
  else if (pixels >= 1_500_000) score += 4;

  // Unsplash likes are a usable proxy for "other people found this good".
  if (candidate.likes >= 500) score += 4;
  else if (candidate.likes >= 100) score += 2;

  return score;
}

/** 5+6+8. Composition, orientation and crop suitability against the role. */
function scoreShape(candidate, entry) {
  const role = roleOf(getCategory(entry.category));
  const aspect = candidate.width / candidate.height;
  const target = role.aspect;

  // How much of the frame survives the crop this role performs.
  const retained = aspect > target ? target / aspect : aspect / target;
  let score = Math.round(retained * 14);

  // A hero needs genuine width to survive a 21:9 crop and a parallax scroll.
  if (role.id === 'hero' || role.id === 'parallax') {
    if (candidate.width < 1600) score -= 10;
    if (aspect < 1.3) score -= 6;
  }
  if (role.orientation === 'portrait' && aspect > 1) score -= 8;
  if (role.orientation === 'landscape' && aspect < 0.95) score -= 8;

  return score;
}

/** 7+10. Subject visibility and authenticity. */
function scoreAuthenticity(candidate, entry, text) {
  let score = 6;
  for (const term of INAUTHENTIC) {
    if (text.includes(term)) {
      score -= 12;
      break;
    }
  }
  if (['wildlife', 'safari'].includes(entry.category)) {
    for (const term of CAPTIVE) {
      if (text.includes(term)) {
        score -= 14;
        break;
      }
    }
  }
  // A candidate with no descriptive text at all is a subject-visibility risk:
  // nothing corroborates what is actually in the frame.
  if (!candidate.description && (candidate.tags ?? []).length === 0) score -= 4;
  return score;
}

/** The disqualifier: another country's landmark. */
function scoreConflict(destination, text) {
  if (destination.slug === REGION.slug) return 0;
  for (const term of conflicts(destination.slug)) {
    if (text.includes(term)) return -40;
  }
  return 0;
}

/** 9. Uniqueness — never reuse a photo already spent on another slot. */
function scoreUniqueness(candidate, usedPhotoKeys) {
  const key = `${candidate.provider}:${candidate.photoId}`;
  return usedPhotoKeys.has(key) ? -1000 : 0;
}

/**
 * Score one candidate. Returns the total plus the breakdown, which the
 * validation report prints so a bad pick can be explained rather than guessed at.
 */
export function scoreCandidate(candidate, entry, destination, usedPhotoKeys = new Set()) {
  const text = haystack(candidate);
  const parts = {
    country: scoreCountry(candidate, destination, text),
    category: scoreCategory(candidate, entry, text),
    quality: scoreQuality(candidate),
    shape: scoreShape(candidate, entry),
    authenticity: scoreAuthenticity(candidate, entry, text),
    conflict: scoreConflict(destination, text),
    uniqueness: scoreUniqueness(candidate, usedPhotoKeys),
  };
  const total = Object.values(parts).reduce((a, b) => a + b, 0);
  return { total, parts };
}

/**
 * Rank a candidate list and return the best acceptable one.
 *
 * @returns {{best: object|null, scored: Array, rejected: number}}
 */
export function rankCandidates(candidates, entry, destination, usedPhotoKeys = new Set()) {
  const scored = candidates
    .map((candidate) => ({
      candidate,
      ...scoreCandidate(candidate, entry, destination, usedPhotoKeys),
    }))
    .sort((a, b) => b.total - a.total);

  const acceptable = scored.filter((s) => s.total >= ACCEPT_THRESHOLD);
  return {
    best: acceptable.length ? acceptable[0] : null,
    scored: scored.slice(0, 5),
    rejected: scored.length - acceptable.length,
  };
}

export const __test__ = { conflictTermsFor, haystack, COUNTRIES };
